[package]
name = "modmailbot_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "*", features = ["derive"] }
serenity = "0.12.4"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "macros"] }
tokio = { version = "1.47.1", features = ["rt-multi-thread"] }
toml = "0.9.4"
reqwest = "0.12.22"
async-trait = "0.1.88"
chrono = { version = "0.4.41", features = ["serde"] }
lazy_static = "1.5.0"

[dependencies.uuid]
version = "1.18.0"
features = ["v4"]
