[bot]
token = "YOUR TOKEN HERE"

# Mode de serveur : "single" pour un seul serveur, "dual" pour deux serveurs séparés
# Mode Mono Serveur (comme avant)
mode = { type = "single", guild_id = 711880297272381856 }

# Mode Double Serveur (nouveau)
# mode = { type = "dual", community_guild_id = 711880297272381856, staff_guild_id = 123456789012345678 }

status = "DM POUR SUPPORT"
typing_proxy_from_user = true
typing_proxy_from_staff = true

[command]
prefix = "!"

[thread]
inbox_category_id = 1376462463847505960
embedded_message = true
user_message_color = "3d54ff"
staff_message_color = "ff3126"
block_quote = true

[notifications]
show_success_on_edit = true
show_partial_success_on_edit = true
show_failure_on_edit = true
show_success_on_reply = true

[language]
default_language = "en"
auto_detect = true
fallback_language = "en"
supported_languages = ["en", "fr", "es", "de"]

[error_handling]
show_detailed_errors = false
log_errors = true
send_error_embeds = true
auto_delete_error_messages = true
error_message_ttl = 30
